#!/bin/sh

changed=0

if ! uci -q get "luci.themes.Liquid" 2>/dev/null; then
	uci set "luci.themes.Liquid=/luci-static/liquid"
	changed=1
fi

if [ "$PKG_UPGRADE" != 1 ] && [ $changed = 1 ]; then
	if ! uci -q get "luci.main.mediaurlbase" 2>/dev/null; then
		uci set "luci.main.mediaurlbase=/luci-static/liquid"
	fi
fi

if [ $changed = 1 ]; then
	uci commit luci
fi

exit 0
